/* eslint-disable max-len */
import {data} from '../src/index';

const testIndices = [0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000];
const testData = [
  {
    'countryyearcode': 'ABW1980',
    'SLE': 0,
    'countrycode': 'ABW',
    'countryname': 'Aruba',
    'year': 1980,
    '': 1000,
    'region': 'LCN',
    'regionname': 'Latin America and Caribbean',
    'incomelevel': 'HIC',
    'incomelevelname': 'High income',
    'GRxGincSC2022': null,
    'GRxGincSC2021': 0,
    'GDP per capita (constant 2015 US$)': null,
    'GRpcUNUWIDER 2022': null,
    'GRpc UNU WIDER': 0,
    'Pop total': 60097,
    'Population ages 00-04, female': 2558,
    'Population ages 00-04, male': 2704,
    'Pop<5': 5262,
    'Population ages 15-19, female': 3403,
    'Population ages 20-24, female': 3002,
    'Population ages 25-29, female': 2778,
    'Population ages 30-34, female': 2733,
    'Population ages 35-39, female': 2115,
    'Population ages 40-44, female': 1877,
    'Population ages 45-49, female': 1721,
    'Female Pop15-49': 17629,
    'Mortality rate, infant (per 1,000 live births)': null,
    'INFANT SURVIVAL ': null,
    'Number of infants surviving to 1yr': null,
    'Birth rate, crude (per 1,000 people)': 22.472,
    'Number of births': 1350.499784,
    'Maternal mortality ratio (modeled estimate, per 100,000 live births)':
      null,
    'Maternal survival per 100,000 live births': null,
    'Maternal survival rate %': null,
    'Mortality rate, under-5 (per 1,000 live births)': null,
    'U5 survival rate (per 1000 live births)': null,
    'U5 survival %': null,
    'Number of children surviving to five ': null,
    'Number of maternal deaths': null,
    'Number of under-five deaths': null,
    'School life expectancy, primary and secondary, both sexes (years)': null,
    'School percent': null,
    'People using at least basic drinking water services (% of population)':
      null,
    'People using safely managed drinking water services (% of population)':
      null,
    'People using at least basic sanitation services (% of population)': null,
    'People using safely managed sanitation services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': null,
    'Control of Corruption: Estimate': null,
    'Government Effectiveness: Estimate': null,
    'Political Stability and Absence of Violence/Terrorism: Estimate': null,
    'Regulatory Quality: Estimate': null,
    'Rule of Law: Estimate': null,
    'Voice and Accountability: Estimate': null,
    'Out of school: Primary school': null,
    'Out of school: Lower school': null,
    'Out of school: Upper school': null,
    'In school: Primary school': null,
    'In school: Lower school': null,
    'In school: Upper school': null,
    'School age population, primary education, both sexes (number)': 6384,
    'School age population, primary education, female (number)': 3119,
    'School age population, primary education, male (number)': 3265,
    'School age population, lower secondary education, both sexes (number)': 2515,
    'School age population, lower secondary education, female (number)': 1230,
    'School age population, lower secondary education, male (number)': 1285,
    'School age population, upper secondary education, both sexes (number)': 4162,
    'School age population, upper secondary education, female (number)': 2041,
    'School age population, upper secondary education, male (number)': 2121,
  },
  {
    'countryyearcode': 'BLZ2014',
    'SLE': 11.4988,
    'countrycode': 'BLZ',
    'countryname': 'Belize',
    'year': 2014,
    '': 1000,
    'region': 'LCN',
    'regionname': 'Latin America and Caribbean',
    'incomelevel': 'UMC',
    'incomelevelname': 'Upper middle income',
    'GRxGincSC2022': 0.285090254,
    'GRxGincSC2021': 0.286714943,
    'GDP per capita (constant 2015 US$)': 4769.914,
    'GRpcUNUWIDER 2022': 1359.855993,
    'GRpc UNU WIDER': 1367.605622,
    'Pop total': 353366,
    'Population ages 00-04, female': 18886,
    'Population ages 00-04, male': 19450,
    'Pop<5': 38336,
    'Population ages 15-19, female': 18946,
    'Population ages 20-24, female': 17458,
    'Population ages 25-29, female': 15662,
    'Population ages 30-34, female': 13650,
    'Population ages 35-39, female': 11574,
    'Population ages 40-44, female': 10524,
    'Population ages 45-49, female': 8672,
    'Female Pop15-49': 96486,
    'Mortality rate, infant (per 1,000 live births)': 13.9,
    'INFANT SURVIVAL ': 986.1,
    'Number of infants surviving to 1yr': 7689.339109,
    'Birth rate, crude (per 1,000 people)': 22.067,
    'Number of births': 7797.727522,
    'Maternal mortality ratio (modeled estimate, per 100,000 live births)': 46,
    'Maternal survival per 100,000 live births': '99,954',
    'Maternal survival rate %': 99.95,
    'Mortality rate, under-5 (per 1,000 live births)': 16.1,
    'U5 survival rate (per 1000 live births)': 983.9,
    'U5 survival %': 98.39,
    'Number of children surviving to five ': 7672.184109,
    'Number of maternal deaths': 4,
    'Number of under-five deaths': 125,
    'School life expectancy, primary and secondary, both sexes (years)': 11.4988,
    'School percent': 67.64,
    'People using at least basic drinking water services (% of population)': 96.5423,
    'People using safely managed drinking water services (% of population)':
      null,
    'People using at least basic sanitation services (% of population)': 86.893,
    'People using safely managed sanitation services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': 95,
    'Control of Corruption: Estimate': -0.1981375,
    'Government Effectiveness: Estimate': -0.6578027,
    'Political Stability and Absence of Violence/Terrorism: Estimate': 0.0485831,
    'Regulatory Quality: Estimate': -0.4965478,
    'Rule of Law: Estimate': -0.7452539,
    'Voice and Accountability: Estimate': 0.5200883,
    'Out of school: Primary school': 0.02,
    'Out of school: Lower school': 0.11,
    'Out of school: Upper school': 0.41,
    'In school: Primary school': 0.98,
    'In school: Lower school': 0.89,
    'In school: Upper school': 0.59,
    'School age population, primary education, both sexes (number)': 46595,
    'School age population, primary education, female (number)': 22992,
    'School age population, primary education, male (number)': 23603,
    'School age population, lower secondary education, both sexes (number)': 31289,
    'School age population, lower secondary education, female (number)': 15593,
    'School age population, lower secondary education, male (number)': 15696,
    'School age population, upper secondary education, both sexes (number)': 15218,
    'School age population, upper secondary education, female (number)': 7608,
    'School age population, upper secondary education, male (number)': 7610,
  },
  {
    'countryyearcode': 'CYM2006',
    'SLE': 10.2121,
    'countrycode': 'CYM',
    'countryname': 'Cayman Islands',
    'year': 2006,
    '': 1000,
    'region': 'LCN',
    'regionname': 'Latin America and Caribbean',
    'incomelevel': 'HIC',
    'incomelevelname': 'High income',
    'GRxGincSC2022': null,
    'GRxGincSC2021': null,
    'GDP per capita (constant 2015 US$)': 91341.3,
    'GRpcUNUWIDER 2022': 0,
    'GRpc UNU WIDER': null,
    'Pop total': 50729,
    'Population ages 00-04, female': null,
    'Population ages 00-04, male': null,
    'Pop<5': 0,
    'Population ages 15-19, female': null,
    'Population ages 20-24, female': null,
    'Population ages 25-29, female': null,
    'Population ages 30-34, female': null,
    'Population ages 35-39, female': null,
    'Population ages 40-44, female': null,
    'Population ages 45-49, female': null,
    'Female Pop15-49': 0,
    'Mortality rate, infant (per 1,000 live births)': null,
    'INFANT SURVIVAL ': null,
    'Number of infants surviving to 1yr': null,
    'Birth rate, crude (per 1,000 people)': 13.4,
    'Number of births': 679.7686,
    'Maternal mortality ratio (modeled estimate, per 100,000 live births)':
      null,
    'Maternal survival per 100,000 live births': null,
    'Maternal survival rate %': null,
    'Mortality rate, under-5 (per 1,000 live births)': null,
    'U5 survival rate (per 1000 live births)': null,
    'U5 survival %': null,
    'Number of children surviving to five ': null,
    'Number of maternal deaths': null,
    'Number of under-five deaths': null,
    'School life expectancy, primary and secondary, both sexes (years)': 10.2121,
    'School percent': 60.07117647,
    'People using at least basic drinking water services (% of population)': 96.125,
    'People using safely managed drinking water services (% of population)':
      null,
    'People using at least basic sanitation services (% of population)': 83.654,
    'People using safely managed sanitation services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': null,
    'Control of Corruption: Estimate': 1.259531,
    'Government Effectiveness: Estimate': 1.285327,
    'Political Stability and Absence of Violence/Terrorism: Estimate': 1.107798,
    'Regulatory Quality: Estimate': 1.350138,
    'Rule of Law: Estimate': 1.080184,
    'Voice and Accountability: Estimate': 0.7828683,
    'Out of school: Primary school': null,
    'Out of school: Lower school': null,
    'Out of school: Upper school': null,
    'In school: Primary school': null,
    'In school: Lower school': null,
    'In school: Upper school': null,
    'School age population, primary education, both sexes (number)': 3793,
    'School age population, primary education, female (number)': 1879,
    'School age population, primary education, male (number)': 1914,
    'School age population, lower secondary education, both sexes (number)': 1909,
    'School age population, lower secondary education, female (number)': 945,
    'School age population, lower secondary education, male (number)': 964,
    'School age population, upper secondary education, both sexes (number)': 1743,
    'School age population, upper secondary education, female (number)': 862,
    'School age population, upper secondary education, male (number)': 881,
  },
  {
    'countryyearcode': 'GIB1998',
    'SLE': 0,
    'countrycode': 'GIB',
    'countryname': 'Gibraltar',
    'year': 1998,
    '': 1000,
    'region': 'ECS',
    'regionname': 'Europe and Central Asia',
    'incomelevel': 'HIC',
    'incomelevelname': 'High income',
    'GRxGincSC2022': null,
    'GRxGincSC2021': null,
    'GDP per capita (constant 2015 US$)': null,
    'GRpcUNUWIDER 2022': 0,
    'GRpc UNU WIDER': null,
    'Pop total': 29945,
    'Population ages 00-04, female': null,
    'Population ages 00-04, male': null,
    'Pop<5': 0,
    'Population ages 15-19, female': null,
    'Population ages 20-24, female': null,
    'Population ages 25-29, female': null,
    'Population ages 30-34, female': null,
    'Population ages 35-39, female': null,
    'Population ages 40-44, female': null,
    'Population ages 45-49, female': null,
    'Female Pop15-49': 0,
    'Mortality rate, infant (per 1,000 live births)': null,
    'INFANT SURVIVAL ': null,
    'Number of infants surviving to 1yr': null,
    'Birth rate, crude (per 1,000 people)': null,
    'Number of births': 0,
    'Maternal mortality ratio (modeled estimate, per 100,000 live births)':
      null,
    'Maternal survival per 100,000 live births': null,
    'Maternal survival rate %': null,
    'Mortality rate, under-5 (per 1,000 live births)': null,
    'U5 survival rate (per 1000 live births)': null,
    'U5 survival %': null,
    'Number of children surviving to five ': null,
    'Number of maternal deaths': null,
    'Number of under-five deaths': null,
    'School life expectancy, primary and secondary, both sexes (years)': 9.609375714285715,
    'School percent': 56.525739495,
    'People using at least basic drinking water services (% of population)':
      null,
    'People using safely managed drinking water services (% of population)':
      null,
    'People using at least basic sanitation services (% of population)': null,
    'People using safely managed sanitation services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': null,
    'Control of Corruption: Estimate': null,
    'Government Effectiveness: Estimate': null,
    'Political Stability and Absence of Violence/Terrorism: Estimate': null,
    'Regulatory Quality: Estimate': null,
    'Rule of Law: Estimate': null,
    'Voice and Accountability: Estimate': null,
    'Out of school: Primary school': null,
    'Out of school: Lower school': null,
    'Out of school: Upper school': null,
    'In school: Primary school': null,
    'In school: Lower school': null,
    'In school: Upper school': null,
    'School age population, primary education, both sexes (number)': 2395,
    'School age population, primary education, female (number)': 1160,
    'School age population, primary education, male (number)': 1235,
    'School age population, lower secondary education, both sexes (number)': 809,
    'School age population, lower secondary education, female (number)': 393,
    'School age population, lower secondary education, male (number)': 416,
    'School age population, upper secondary education, both sexes (number)': 872,
    'School age population, upper secondary education, female (number)': 424,
    'School age population, upper secondary education, male (number)': 448,
  },
  {
    'countryyearcode': 'ITA1990',
    'SLE': 11.3405,
    'countrycode': 'ITA',
    'countryname': 'Italy',
    'year': 1990,
    '': 1000,
    'region': 'ECS',
    'regionname': 'Europe and Central Asia',
    'incomelevel': 'HIC',
    'incomelevelname': 'High income',
    'GRxGincSC2022': 0.401683187,
    'GRxGincSC2021': 0.402215468,
    'GDP per capita (constant 2015 US$)': 27490.63,
    'GRpcUNUWIDER 2022': 11042.52387,
    'GRpc UNU WIDER': 11057.15661,
    'Pop total': 56719240,
    'Population ages 00-04, female': 1360380,
    'Population ages 00-04, male': 1442083,
    'Pop<5': 2802463,
    'Population ages 15-19, female': 2100881,
    'Population ages 20-24, female': 2248951,
    'Population ages 25-29, female': 2243811,
    'Population ages 30-34, female': 2024227,
    'Population ages 35-39, female': 1930743,
    'Population ages 40-44, female': 2002073,
    'Population ages 45-49, female': 1725371,
    'Female Pop15-49': 14276057,
    'Mortality rate, infant (per 1,000 live births)': 8.4,
    'INFANT SURVIVAL ': 991.6,
    'Number of infants surviving to 1yr': 562427.9838,
    'Birth rate, crude (per 1,000 people)': 10,
    'Number of births': 567192.4,
    'Maternal mortality ratio (modeled estimate, per 100,000 live births)':
      null,
    'Maternal survival per 100,000 live births': null,
    'Maternal survival rate %': null,
    'Mortality rate, under-5 (per 1,000 live births)': 9.7,
    'U5 survival rate (per 1000 live births)': 990.3,
    'U5 survival %': 99.03,
    'Number of children surviving to five ': 561690.6337,
    'Number of maternal deaths': null,
    'Number of under-five deaths': 5422,
    'School life expectancy, primary and secondary, both sexes (years)': 11.3405,
    'School percent': 66.70882353,
    'People using at least basic drinking water services (% of population)':
      null,
    'People using safely managed drinking water services (% of population)':
      null,
    'People using at least basic sanitation services (% of population)': null,
    'People using safely managed sanitation services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': 83,
    'Control of Corruption: Estimate': null,
    'Government Effectiveness: Estimate': null,
    'Political Stability and Absence of Violence/Terrorism: Estimate': null,
    'Regulatory Quality: Estimate': null,
    'Rule of Law: Estimate': null,
    'Voice and Accountability: Estimate': null,
    'Out of school: Primary school': null,
    'Out of school: Lower school': null,
    'Out of school: Upper school': null,
    'In school: Primary school': null,
    'In school: Lower school': null,
    'In school: Upper school': null,
    'School age population, primary education, both sexes (number)': 3193507,
    'School age population, primary education, female (number)': 1554401,
    'School age population, primary education, male (number)': 1639106,
    'School age population, lower secondary education, both sexes (number)': 2220212,
    'School age population, lower secondary education, female (number)': 1083438,
    'School age population, lower secondary education, male (number)': 1136774,
    'School age population, upper secondary education, both sexes (number)': 4311590,
    'School age population, upper secondary education, female (number)': 2109196,
    'School age population, upper secondary education, male (number)': 2202394,
  },
  {
    'countryyearcode': 'MAF1982',
    'SLE': 0,
    'countrycode': 'MAF',
    'countryname': 'St. Martin (French part)',
    'year': 1982,
    '': 1000,
    'region': 'LCN',
    'regionname': 'Latin America and Caribbean',
    'incomelevel': 'HIC',
    'incomelevelname': 'High income',
    'GRxGincSC2022': null,
    'GRxGincSC2021': null,
    'GDP per capita (constant 2015 US$)': null,
    'GRpcUNUWIDER 2022': 0,
    'GRpc UNU WIDER': null,
    'Pop total': 8372,
    'Population ages 00-04, female': null,
    'Population ages 00-04, male': null,
    'Pop<5': 0,
    'Population ages 15-19, female': null,
    'Population ages 20-24, female': null,
    'Population ages 25-29, female': null,
    'Population ages 30-34, female': null,
    'Population ages 35-39, female': null,
    'Population ages 40-44, female': null,
    'Population ages 45-49, female': null,
    'Female Pop15-49': 0,
    'Mortality rate, infant (per 1,000 live births)': null,
    'INFANT SURVIVAL ': null,
    'Number of infants surviving to 1yr': null,
    'Birth rate, crude (per 1,000 people)': 21,
    'Number of births': 175.812,
    'Maternal mortality ratio (modeled estimate, per 100,000 live births)':
      null,
    'Maternal survival per 100,000 live births': null,
    'Maternal survival rate %': null,
    'Mortality rate, under-5 (per 1,000 live births)': null,
    'U5 survival rate (per 1000 live births)': null,
    'U5 survival %': null,
    'Number of children surviving to five ': null,
    'Number of maternal deaths': null,
    'Number of under-five deaths': null,
    'School life expectancy, primary and secondary, both sexes (years)': 0,
    'School percent': 0,
    'People using at least basic drinking water services (% of population)':
      null,
    'People using safely managed drinking water services (% of population)':
      null,
    'People using at least basic sanitation services (% of population)': null,
    'People using safely managed sanitation services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': null,
    'Control of Corruption: Estimate': null,
    'Government Effectiveness: Estimate': null,
    'Political Stability and Absence of Violence/Terrorism: Estimate': null,
    'Regulatory Quality: Estimate': null,
    'Rule of Law: Estimate': null,
    'Voice and Accountability: Estimate': null,
    'Out of school: Primary school': null,
    'Out of school: Lower school': null,
    'Out of school: Upper school': null,
    'In school: Primary school': null,
    'In school: Lower school': null,
    'In school: Upper school': null,
    'School age population, primary education, both sexes (number)': null,
    'School age population, primary education, female (number)': null,
    'School age population, primary education, male (number)': null,
    'School age population, lower secondary education, both sexes (number)':
      null,
    'School age population, lower secondary education, female (number)': null,
    'School age population, lower secondary education, male (number)': null,
    'School age population, upper secondary education, both sexes (number)':
      null,
    'School age population, upper secondary education, female (number)': null,
    'School age population, upper secondary education, male (number)': null,
  },
  {
    'countryyearcode': 'NIC2016',
    'SLE': 0,
    'countrycode': 'NIC',
    'countryname': 'Nicaragua',
    'year': 2016,
    '': 1000,
    'region': 'LCN',
    'regionname': 'Latin America and Caribbean',
    'incomelevel': 'LMC',
    'incomelevelname': 'Lower middle income',
    'GRxGincSC2022': null,
    'GRxGincSC2021': null,
    'GDP per capita (constant 2015 US$)': 2115.946,
    'GRpcUNUWIDER 2022': null,
    'GRpc UNU WIDER': null,
    'Pop total': 6303970,
    'Population ages 00-04, female': 327305,
    'Population ages 00-04, male': 341969,
    'Pop<5': 669274,
    'Population ages 15-19, female': 292518,
    'Population ages 20-24, female': 293995,
    'Population ages 25-29, female': 283535,
    'Population ages 30-34, female': 268761,
    'Population ages 35-39, female': 233634,
    'Population ages 40-44, female': 195016,
    'Population ages 45-49, female': 158699,
    'Female Pop15-49': 1726158,
    'Mortality rate, infant (per 1,000 live births)': 16,
    'INFANT SURVIVAL ': 984,
    'Number of infants surviving to 1yr': 133168.2899,
    'Birth rate, crude (per 1,000 people)': 21.468,
    'Number of births': 135333.628,
    'Maternal mortality ratio (modeled estimate, per 100,000 live births)': 100,
    'Maternal survival per 100,000 live births': '99,900',
    'Maternal survival rate %': 99.9,
    'Mortality rate, under-5 (per 1,000 live births)': 18.6,
    'U5 survival rate (per 1000 live births)': 981.4,
    'U5 survival %': 98.14,
    'Number of children surviving to five ': 132816.4225,
    'Number of maternal deaths': 140,
    'Number of under-five deaths': 2527,
    'School life expectancy, primary and secondary, both sexes (years)': null,
    'School percent': null,
    'People using at least basic drinking water services (% of population)': 81.416,
    'People using safely managed drinking water services (% of population)': 55.2551,
    'People using at least basic sanitation services (% of population)': 72.8319,
    'People using safely managed sanitation services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': 98,
    'Control of Corruption: Estimate': -0.8713118,
    'Government Effectiveness: Estimate': -0.6887094,
    'Political Stability and Absence of Violence/Terrorism: Estimate':
      -0.0887977,
    'Regulatory Quality: Estimate': -0.5067052,
    'Rule of Law: Estimate': -0.6444019,
    'Voice and Accountability: Estimate': -0.680073,
    'Out of school: Primary school': 0.01,
    'Out of school: Lower school': 0.02,
    'Out of school: Upper school': 0.08,
    'In school: Primary school': 0.99,
    'In school: Lower school': 0.98,
    'In school: Upper school': 0.92,
    'School age population, primary education, both sexes (number)': 775231,
    'School age population, primary education, female (number)': 376630,
    'School age population, primary education, male (number)': 398601,
    'School age population, lower secondary education, both sexes (number)': 370776,
    'School age population, lower secondary education, female (number)': 179445,
    'School age population, lower secondary education, male (number)': 191331,
    'School age population, upper secondary education, both sexes (number)': 243418,
    'School age population, upper secondary education, female (number)': 117701,
    'School age population, upper secondary education, male (number)': 125717,
  },
  {
    'countryyearcode': 'SAU2008',
    'SLE': 0,
    'countrycode': 'SAU',
    'countryname': 'Saudi Arabia',
    'year': 2008,
    '': 1000,
    'region': 'MEA',
    'regionname': 'Middle East and North Africa',
    'incomelevel': 'HIC',
    'incomelevelname': 'High income',
    'GRxGincSC2022': 0.564459324,
    'GRxGincSC2021': 0.564459035,
    'GDP per capita (constant 2015 US$)': 19117.93,
    'GRpcUNUWIDER 2022': 10791.29385,
    'GRpc UNU WIDER': 10791.28831,
    'Pop total': 25888535,
    'Population ages 00-04, female': 1403972,
    'Population ages 00-04, male': 1444824,
    'Pop<5': 2848796,
    'Population ages 15-19, female': 1268161,
    'Population ages 20-24, female': 1090553,
    'Population ages 25-29, female': 1016104,
    'Population ages 30-34, female': 1022541,
    'Population ages 35-39, female': 836985,
    'Population ages 40-44, female': 627390,
    'Population ages 45-49, female': 451217,
    'Female Pop15-49': 6312951,
    'Mortality rate, infant (per 1,000 live births)': 11.9,
    'INFANT SURVIVAL ': 988.1,
    'Number of infants surviving to 1yr': 589450.5728,
    'Birth rate, crude (per 1,000 people)': 23.043,
    'Number of births': 596549.512,
    'Maternal mortality ratio (modeled estimate, per 100,000 live births)': 20,
    'Maternal survival per 100,000 live births': '99,980',
    'Maternal survival rate %': 99.98,
    'Mortality rate, under-5 (per 1,000 live births)': 13.8,
    'U5 survival rate (per 1000 live births)': 986.2,
    'U5 survival %': 98.62,
    'Number of children surviving to five ': 588317.1287,
    'Number of maternal deaths': 120,
    'Number of under-five deaths': 8190,
    'School life expectancy, primary and secondary, both sexes (years)': 11.8477,
    'School percent': 69.692352945,
    'People using at least basic drinking water services (% of population)': 98.4275,
    'People using safely managed drinking water services (% of population)':
      null,
    'People using at least basic sanitation services (% of population)': 99.0446,
    'People using safely managed sanitation services (% of population)': 44.5535,
    'Immunization, DPT (% of children ages 12-23 months)': 98,
    'Control of Corruption: Estimate': -0.0084042,
    'Government Effectiveness: Estimate': -0.0889558,
    'Political Stability and Absence of Violence/Terrorism: Estimate':
      -0.3371701,
    'Regulatory Quality: Estimate': 0.1200698,
    'Rule of Law: Estimate': 0.0746007,
    'Voice and Accountability: Estimate': -1.729974,
    'Out of school: Primary school': 0.09,
    'Out of school: Lower school': 0.09,
    'Out of school: Upper school': 0.19,
    'In school: Primary school': 0.91,
    'In school: Lower school': 0.91,
    'In school: Upper school': 0.81,
    'School age population, primary education, both sexes (number)': 3126356,
    'School age population, primary education, female (number)': 1540412,
    'School age population, primary education, male (number)': 1585944,
    'School age population, lower secondary education, both sexes (number)': 1608581,
    'School age population, lower secondary education, female (number)': 794731,
    'School age population, lower secondary education, male (number)': 813850,
    'School age population, upper secondary education, both sexes (number)': 1545574,
    'School age population, upper secondary education, female (number)': 763992,
    'School age population, upper secondary education, male (number)': 781582,
  },
  {
    'countryyearcode': 'TJK2000',
    'SLE': 8.81733,
    'countrycode': 'TJK',
    'countryname': 'Tajikistan',
    'year': 2000,
    '': 1000,
    'region': 'ECS',
    'regionname': 'Europe and Central Asia',
    'incomelevel': 'LIC',
    'incomelevelname': 'Low income',
    'GRxGincSC2022': 0.135030437,
    'GRxGincSC2021': 0.135030437,
    'GDP per capita (constant 2015 US$)': 434.2652,
    'GRpcUNUWIDER 2022': 58.63901981,
    'GRpc UNU WIDER': 58.63901981,
    'Pop total': 6216329,
    'Population ages 00-04, female': 436769,
    'Population ages 00-04, male': 455668,
    'Pop<5': 892437,
    'Population ages 15-19, female': 348142,
    'Population ages 20-24, female': 271614,
    'Population ages 25-29, female': 235417,
    'Population ages 30-34, female': 209262,
    'Population ages 35-39, female': 190552,
    'Population ages 40-44, female': 152400,
    'Population ages 45-49, female': 108579,
    'Female Pop15-49': 1515966,
    'Mortality rate, infant (per 1,000 live births)': 67.6,
    'INFANT SURVIVAL ': 932.4,
    'Number of infants surviving to 1yr': 177499.9244,
    'Birth rate, crude (per 1,000 people)': 30.624,
    'Number of births': 190368.8593,
    'Maternal mortality ratio (modeled estimate, per 100,000 live births)': 53,
    'Maternal survival per 100,000 live births': '99,947',
    'Maternal survival rate %': 99.95,
    'Mortality rate, under-5 (per 1,000 live births)': 83.6,
    'U5 survival rate (per 1000 live births)': 916.4,
    'U5 survival %': 91.64,
    'Number of children surviving to five ': 174454.0227,
    'Number of maternal deaths': 100,
    'Number of under-five deaths': 15881,
    'School life expectancy, primary and secondary, both sexes (years)': 8.81733,
    'School percent': 51.86664706,
    'People using at least basic drinking water services (% of population)': 56.5062,
    'People using safely managed drinking water services (% of population)': 35.9905,
    'People using at least basic sanitation services (% of population)': 89.9072,
    'People using safely managed sanitation services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': 83,
    'Control of Corruption: Estimate': -1.275289,
    'Government Effectiveness: Estimate': -1.19373,
    'Political Stability and Absence of Violence/Terrorism: Estimate':
      -1.648767,
    'Regulatory Quality: Estimate': -1.117777,
    'Rule of Law: Estimate': -1.390418,
    'Voice and Accountability: Estimate': -1.382805,
    'Out of school: Primary school': 0.07,
    'Out of school: Lower school': 0.12,
    'Out of school: Upper school': 0.34,
    'In school: Primary school': 0.93,
    'In school: Lower school': 0.88,
    'In school: Upper school': 0.66,
    'School age population, primary education, both sexes (number)': 717265,
    'School age population, primary education, female (number)': 353691,
    'School age population, primary education, male (number)': 363574,
    'School age population, lower secondary education, both sexes (number)': 816270,
    'School age population, lower secondary education, female (number)': 403845,
    'School age population, lower secondary education, male (number)': 412425,
    'School age population, upper secondary education, both sexes (number)': 275023,
    'School age population, upper secondary education, female (number)': 136265,
    'School age population, upper secondary education, male (number)': 138758,
  },
  {
    'countryyearcode': 'ZMB1992',
    'SLE': 0,
    'countrycode': 'ZMB',
    'countryname': 'Zambia',
    'year': 1992,
    '': 1000,
    'region': 'SSF',
    'regionname': 'Sub-Saharan Africa',
    'incomelevel': 'LMC',
    'incomelevelname': 'Lower middle income',
    'GRxGincSC2022': 0.183510545,
    'GRxGincSC2021': 0.183510545,
    'GDP per capita (constant 2015 US$)': 795.1403,
    'GRpcUNUWIDER 2022': 145.9166297,
    'GRpc UNU WIDER': 145.9166297,
    'Pop total': 8451346,
    'Population ages 00-04, female': 773864,
    'Population ages 00-04, male': 782658,
    'Pop<5': 1556522,
    'Population ages 15-19, female': 472241,
    'Population ages 20-24, female': 379663,
    'Population ages 25-29, female': 310317,
    'Population ages 30-34, female': 251849,
    'Population ages 35-39, female': 196964,
    'Population ages 40-44, female': 155444,
    'Population ages 45-49, female': 124874,
    'Female Pop15-49': 1891352,
    'Mortality rate, infant (per 1,000 live births)': 107.1,
    'INFANT SURVIVAL ': 892.9,
    'Number of infants surviving to 1yr': 343050.5631,
    'Birth rate, crude (per 1,000 people)': 45.46,
    'Number of births': 384198.1892,
    'Maternal mortality ratio (modeled estimate, per 100,000 live births)':
      null,
    'Maternal survival per 100,000 live births': null,
    'Maternal survival rate %': null,
    'Mortality rate, under-5 (per 1,000 live births)': 181.9,
    'U5 survival rate (per 1000 live births)': 818.1,
    'U5 survival %': 81.81,
    'Number of children surviving to five ': 314312.5386,
    'Number of maternal deaths': null,
    'Number of under-five deaths': 66725,
    'School life expectancy, primary and secondary, both sexes (years)': 7.294155,
    'School percent': 42.906794115,
    'People using at least basic drinking water services (% of population)':
      null,
    'People using safely managed drinking water services (% of population)':
      null,
    'People using at least basic sanitation services (% of population)': null,
    'People using safely managed sanitation services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': 83,
    'Control of Corruption: Estimate': null,
    'Government Effectiveness: Estimate': null,
    'Political Stability and Absence of Violence/Terrorism: Estimate': null,
    'Regulatory Quality: Estimate': null,
    'Rule of Law: Estimate': null,
    'Voice and Accountability: Estimate': null,
    'Out of school: Primary school': null,
    'Out of school: Lower school': null,
    'Out of school: Upper school': null,
    'In school: Primary school': null,
    'In school: Lower school': null,
    'In school: Upper school': null,
    'School age population, primary education, both sexes (number)': 1673382,
    'School age population, primary education, female (number)': 830360,
    'School age population, primary education, male (number)': 843022,
    'School age population, lower secondary education, both sexes (number)': 418628,
    'School age population, lower secondary education, female (number)': 207689,
    'School age population, lower secondary education, male (number)': 210939,
    'School age population, upper secondary education, both sexes (number)': 569348,
    'School age population, upper secondary education, female (number)': 283202,
    'School age population, upper secondary education, male (number)': 286146,
  },
];

testIndices.forEach((index, i) => {
  test('data row is as expected', () => {
    expect(data[index]).toStrictEqual(testData[i]);
  });
});
