/* eslint-disable max-len */
import {data} from '../src/index';

const testIndices = [0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000];
const testData = [
  {
    countryyearcode: 'ABW1980',
    countryname: 'Aruba',
    countrycode: 'ABW',
    'Government revenue per capita (constant 2015 USD)': null,
    year: 1980,
    region: 'LCN',
    incomelevel: 'HIC',
    'People using at least basic sanitation services (% of population)': null,
    'People using safely managed sanitation services (% of population)': null,
    'People using at least basic drinking water services (% of population)': null,
    'People using safely managed drinking water services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': null,
    'School percent': null,
    'U5 survival %': null,
    'Maternal survival rate %': null,
    'Government Effectiveness: Estimate': null,
    'Control of Corruption: Estimate': null,
    'Political Stability and Absence of Violence/Terrorism: Estimate': null,
    'Regulatory Quality: Estimate': null,
    'Rule of Law: Estimate': null,
    'Voice and Accountability: Estimate': null,
    'Pop total': 62267,
    'Pop<5': 6356,
    'Female Pop15-49': 17769,
    'Number of infants surviving to 1yr': 1281,
    'Number of births': 1374,
    'Number of children surviving to five ': 1234,
    'Number of under-five deaths': null,
    'Number of maternal deaths': null,
    'In school: Primary school': null,
    'In school: Lower school': null,
    'In school: Upper school': null,
    'School age population, primary education, both sexes (number)': 6384,
    'School age population, primary education, female (number)': 3119,
    'School age population, primary education, male (number)': 3265,
    'School age population, lower secondary education, both sexes (number)': 2515,
    'School age population, lower secondary education, female (number)': 1230,
    'School age population, lower secondary education, male (number)': 1285,
    'School age population, upper secondary education, both sexes (number)': 4162,
    'School age population, upper secondary education, female (number)': 2041,
    'School age population, upper secondary education, male (number)': 2121,
    'Maternal mortality ratio (per 100,000 live births)': null,
    'Maternal survival per 100,000 live births': null,
    'U5 mortality rate(per 1,000 live births)': null,
    'U5 survival rate (per 1000 live births)': null,
    'Infant mortality rate (per 1000 live births)': null,
    'Infant survival (per 1000 live births)': null,
    'Infant survival rate%': null,
    INVPRIMARYTEACHERS: null,
    PRIMARYTEACHERS: null,
    INVLOWERTEACHERS: null,
    LOWERTEACHERS: null,
    INVUPPERTEACHERS: null,
    '': null
  },
  {
    countryyearcode: 'BLZ1991',
    countryname: 'Belize',
    countrycode: 'BLZ',
    'Government revenue per capita (constant 2015 USD)': 1098.92,
    year: 1991,
    region: 'LCN',
    incomelevel: 'UMC',
    'People using at least basic sanitation services (% of population)': null,
    'People using safely managed sanitation services (% of population)': null,
    'People using at least basic drinking water services (% of population)': null,
    'People using safely managed drinking water services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': 82,
    'School percent': 61.94,
    'U5 survival %': 96.39,
    'Maternal survival rate %': null,
    'Government Effectiveness: Estimate': null,
    'Control of Corruption: Estimate': null,
    'Political Stability and Absence of Violence/Terrorism: Estimate': null,
    'Regulatory Quality: Estimate': null,
    'Rule of Law: Estimate': null,
    'Voice and Accountability: Estimate': null,
    'Pop total': 186462,
    'Pop<5': 30100,
    'Female Pop15-49': 42007,
    'Number of infants surviving to 1yr': 6112,
    'Number of births': 6609,
    'Number of children surviving to five ': 5708,
    'Number of under-five deaths': 238,
    'Number of maternal deaths': null,
    'In school: Primary school': null,
    'In school: Lower school': null,
    'In school: Upper school': null,
    'School age population, primary education, both sexes (number)': 32575,
    'School age population, primary education, female (number)': 16110,
    'School age population, primary education, male (number)': 16465,
    'School age population, lower secondary education, both sexes (number)': 18536,
    'School age population, lower secondary education, female (number)': 9176,
    'School age population, lower secondary education, male (number)': 9360,
    'School age population, upper secondary education, both sexes (number)': 8706,
    'School age population, upper secondary education, female (number)': 4335,
    'School age population, upper secondary education, male (number)': 4371,
    'Maternal mortality ratio (per 100,000 live births)': null,
    'Maternal survival per 100,000 live births': null,
    'U5 mortality rate(per 1,000 live births)': 36.1,
    'U5 survival rate (per 1000 live births)': 963.9,
    'Infant mortality rate (per 1000 live births)': 29.6,
    'Infant survival (per 1000 live births)': 970.4,
    'Infant survival rate%': 97.04,
    INVPRIMARYTEACHERS: null,
    PRIMARYTEACHERS: null,
    INVLOWERTEACHERS: null,
    LOWERTEACHERS: null,
    INVUPPERTEACHERS: null,
    '': null
  },
  {
    countryyearcode: 'CYM2002',
    countryname: 'Cayman Islands',
    countrycode: 'CYM',
    'Government revenue per capita (constant 2015 USD)': 0,
    year: 2002,
    region: 'LCN',
    incomelevel: 'HIC',
    'People using at least basic sanitation services (% of population)': 83.65,
    'People using safely managed sanitation services (% of population)': null,
    'People using at least basic drinking water services (% of population)': 96.13,
    'People using safely managed drinking water services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': null,
    'School percent': 62.54,
    'U5 survival %': null,
    'Maternal survival rate %': null,
    'Government Effectiveness: Estimate': 1.9008,
    'Control of Corruption: Estimate': 1.3107,
    'Political Stability and Absence of Violence/Terrorism: Estimate': 0.7926,
    'Regulatory Quality: Estimate': 1.4225,
    'Rule of Law: Estimate': 1.4694,
    'Voice and Accountability: Estimate': 1.5733,
    'Pop total': 42456,
    'Pop<5': 2993,
    'Female Pop15-49': 13687,
    'Number of infants surviving to 1yr': 639,
    'Number of births': 578,
    'Number of children surviving to five ': 562,
    'Number of under-five deaths': null,
    'Number of maternal deaths': null,
    'In school: Primary school': 0,
    'In school: Lower school': 0,
    'In school: Upper school': 0,
    'School age population, primary education, both sexes (number)': 3752,
    'School age population, primary education, female (number)': 1860,
    'School age population, primary education, male (number)': 1892,
    'School age population, lower secondary education, both sexes (number)': 1519,
    'School age population, lower secondary education, female (number)': 750,
    'School age population, lower secondary education, male (number)': 769,
    'School age population, upper secondary education, both sexes (number)': 1362,
    'School age population, upper secondary education, female (number)': 685,
    'School age population, upper secondary education, male (number)': 677,
    'Maternal mortality ratio (per 100,000 live births)': null,
    'Maternal survival per 100,000 live births': null,
    'U5 mortality rate(per 1,000 live births)': null,
    'U5 survival rate (per 1000 live births)': null,
    'Infant mortality rate (per 1000 live births)': null,
    'Infant survival (per 1000 live births)': null,
    'Infant survival rate%': null,
    INVPRIMARYTEACHERS: 0.063965885,
    PRIMARYTEACHERS: 15.63333333,
    INVLOWERTEACHERS: 0.074391047,
    LOWERTEACHERS: 13.44247788,
    INVUPPERTEACHERS: 0.086637298,
    '': 11.54237288
  },
  {
    countryyearcode: 'GHA2013',
    countryname: 'Ghana',
    countrycode: 'GHA',
    'Government revenue per capita (constant 2015 USD)': 243.41,
    year: 2013,
    region: 'SSF',
    incomelevel: 'LMC',
    'People using at least basic sanitation services (% of population)': 17.29,
    'People using safely managed sanitation services (% of population)': 10.06,
    'People using at least basic drinking water services (% of population)': 77.92,
    'People using safely managed drinking water services (% of population)': 29.93,
    'Immunization, DPT (% of children ages 12-23 months)': 90,
    'School percent': 62.68,
    'U5 survival %': 93.95,
    'Maternal survival rate %': 99.7,
    'Government Effectiveness: Estimate': -0.1369,
    'Control of Corruption: Estimate': -0.0966,
    'Political Stability and Absence of Violence/Terrorism: Estimate': 0.0606,
    'Regulatory Quality: Estimate': 0.0618,
    'Rule of Law: Estimate': 0.1543,
    'Voice and Accountability: Estimate': 0.4389,
    'Pop total': 27525597,
    'Pop<5': 4044686,
    'Female Pop15-49': 6894918,
    'Number of infants surviving to 1yr': 833318,
    'Number of births': 895716,
    'Number of children surviving to five ': 742554,
    'Number of under-five deaths': 52633,
    'Number of maternal deaths': 2700,
    'In school: Primary school': 0.84,
    'In school: Lower school': 0.81,
    'In school: Upper school': 0.6,
    'School age population, primary education, both sexes (number)': 3869823,
    'School age population, primary education, female (number)': 1894842,
    'School age population, primary education, male (number)': 1974981,
    'School age population, lower secondary education, both sexes (number)': 1791906,
    'School age population, lower secondary education, female (number)': 876547,
    'School age population, lower secondary education, male (number)': 915359,
    'School age population, upper secondary education, both sexes (number)': 1685832,
    'School age population, upper secondary education, female (number)': 824137,
    'School age population, upper secondary education, male (number)': 861695,
    'Maternal mortality ratio (per 100,000 live births)': 305,
    'Maternal survival per 100,000 live births': 99695,
    'U5 mortality rate(per 1,000 live births)': 60.5,
    'U5 survival rate (per 1000 live births)': 939.5,
    'Infant mortality rate (per 1000 live births)': 42.2,
    'Infant survival (per 1000 live births)': 957.8,
    'Infant survival rate%': 95.78,
    INVPRIMARYTEACHERS: 0.033489645,
    PRIMARYTEACHERS: 29.85997577,
    INVLOWERTEACHERS: 0.052344822,
    LOWERTEACHERS: 19.10408648,
    INVUPPERTEACHERS: 0.024107384,
    '': 41.48106592
  },
  {
    countryyearcode: 'ISR1981',
    countryname: 'Israel',
    countrycode: 'ISR',
    'Government revenue per capita (constant 2015 USD)': null,
    year: 1981,
    region: 'MEA',
    incomelevel: 'HIC',
    'People using at least basic sanitation services (% of population)': null,
    'People using safely managed sanitation services (% of population)': null,
    'People using at least basic drinking water services (% of population)': null,
    'People using safely managed drinking water services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': 91,
    'School percent': 65.75,
    'U5 survival %': 98.27,
    'Maternal survival rate %': null,
    'Government Effectiveness: Estimate': null,
    'Control of Corruption: Estimate': null,
    'Political Stability and Absence of Violence/Terrorism: Estimate': null,
    'Regulatory Quality: Estimate': null,
    'Rule of Law: Estimate': null,
    'Voice and Accountability: Estimate': null,
    'Pop total': 3956000,
    'Pop<5': 455265,
    'Female Pop15-49': 928288,
    'Number of infants surviving to 1yr': 87659,
    'Number of births': 94807,
    'Number of children surviving to five ': 91618,
    'Number of under-five deaths': 1646,
    'Number of maternal deaths': null,
    'In school: Primary school': null,
    'In school: Lower school': null,
    'In school: Upper school': null,
    'School age population, primary education, both sexes (number)': 478069,
    'School age population, primary education, female (number)': 232911,
    'School age population, primary education, male (number)': 245158,
    'School age population, lower secondary education, both sexes (number)': 201482,
    'School age population, lower secondary education, female (number)': 97885,
    'School age population, lower secondary education, male (number)': 103597,
    'School age population, upper secondary education, both sexes (number)': 194927,
    'School age population, upper secondary education, female (number)': 94599,
    'School age population, upper secondary education, male (number)': 100328,
    'Maternal mortality ratio (per 100,000 live births)': null,
    'Maternal survival per 100,000 live births': null,
    'U5 mortality rate(per 1,000 live births)': 17.3,
    'U5 survival rate (per 1000 live births)': 982.7,
    'Infant mortality rate (per 1000 live births)': 14.7,
    'Infant survival (per 1000 live births)': 985.3,
    'Infant survival rate%': 98.53,
    INVPRIMARYTEACHERS: 0.086740617,
    PRIMARYTEACHERS: 11.52862448,
    INVLOWERTEACHERS: null,
    LOWERTEACHERS: null,
    INVUPPERTEACHERS: null,
    '': null
  },
  {
    countryyearcode: 'LVA1992',
    countryname: 'Latvia',
    countrycode: 'LVA',
    'Government revenue per capita (constant 2015 USD)': null,
    year: 1992,
    region: 'ECS',
    incomelevel: 'HIC',
    'People using at least basic sanitation services (% of population)': null,
    'People using safely managed sanitation services (% of population)': null,
    'People using at least basic drinking water services (% of population)': null,
    'People using safely managed drinking water services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': 87,
    'School percent': 65.15,
    'U5 survival %': 98.05,
    'Maternal survival rate %': null,
    'Government Effectiveness: Estimate': null,
    'Control of Corruption: Estimate': null,
    'Political Stability and Absence of Violence/Terrorism: Estimate': null,
    'Regulatory Quality: Estimate': null,
    'Rule of Law: Estimate': null,
    'Voice and Accountability: Estimate': null,
    'Pop total': 2614338,
    'Pop<5': 184100,
    'Female Pop15-49': 636881,
    'Number of infants surviving to 1yr': 35710,
    'Number of births': 32991,
    'Number of children surviving to five ': 41826,
    'Number of under-five deaths': 691,
    'Number of maternal deaths': null,
    'In school: Primary school': null,
    'In school: Lower school': null,
    'In school: Upper school': null,
    'School age population, primary education, both sexes (number)': 152378,
    'School age population, primary education, female (number)': 74608,
    'School age population, primary education, male (number)': 77770,
    'School age population, lower secondary education, both sexes (number)': 171058,
    'School age population, lower secondary education, female (number)': 84296,
    'School age population, lower secondary education, male (number)': 86762,
    'School age population, upper secondary education, both sexes (number)': 109937,
    'School age population, upper secondary education, female (number)': 53901,
    'School age population, upper secondary education, male (number)': 56036,
    'Maternal mortality ratio (per 100,000 live births)': null,
    'Maternal survival per 100,000 live births': null,
    'U5 mortality rate(per 1,000 live births)': 19.5,
    'U5 survival rate (per 1000 live births)': 980.5,
    'Infant mortality rate (per 1000 live births)': 15.2,
    'Infant survival (per 1000 live births)': 984.8,
    'Infant survival rate%': 98.48,
    INVPRIMARYTEACHERS: 0.062134954,
    PRIMARYTEACHERS: 16.09400084,
    INVLOWERTEACHERS: 0.1014802,
    LOWERTEACHERS: 9.854139063,
    INVUPPERTEACHERS: 0.098392716,
    '': 10.16335398
  },
  {
    countryyearcode: 'NER2003',
    countryname: 'Niger',
    countrycode: 'NER',
    'Government revenue per capita (constant 2015 USD)': 33.25,
    year: 2003,
    region: 'SSF',
    incomelevel: 'LIC',
    'People using at least basic sanitation services (% of population)': 6.87,
    'People using safely managed sanitation services (% of population)': 7.96,
    'People using at least basic drinking water services (% of population)': 39.19,
    'People using safely managed drinking water services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': 41,
    'School percent': 17.73,
    'U5 survival %': 80.5,
    'Maternal survival rate %': 99.14,
    'Government Effectiveness: Estimate': -0.6632,
    'Control of Corruption: Estimate': -0.9164,
    'Political Stability and Absence of Violence/Terrorism: Estimate': 0.0422,
    'Regulatory Quality: Estimate': -0.73,
    'Rule of Law: Estimate': -0.5225,
    'Voice and Accountability: Estimate': -0.156,
    'Pop total': 12900790,
    'Pop<5': 2630270,
    'Female Pop15-49': 2760624,
    'Number of infants surviving to 1yr': 560735,
    'Number of births': 664234,
    'Number of children surviving to five ': 434484,
    'Number of under-five deaths': 121119,
    'Number of maternal deaths': 5700,
    'In school: Primary school': 0.35,
    'In school: Lower school': 0.14,
    'In school: Upper school': 0.05,
    'School age population, primary education, both sexes (number)': 2007424,
    'School age population, primary education, female (number)': 986546,
    'School age population, primary education, male (number)': 1020878,
    'School age population, lower secondary education, both sexes (number)': 1071973,
    'School age population, lower secondary education, female (number)': 534849,
    'School age population, lower secondary education, male (number)': 537124,
    'School age population, upper secondary education, both sexes (number)': 689364,
    'School age population, upper secondary education, female (number)': 360595,
    'School age population, upper secondary education, male (number)': 328769,
    'Maternal mortality ratio (per 100,000 live births)': 863,
    'Maternal survival per 100,000 live births': 99137,
    'U5 mortality rate(per 1,000 live births)': 195,
    'U5 survival rate (per 1000 live births)': 805,
    'Infant mortality rate (per 1000 live births)': 86.9,
    'Infant survival (per 1000 live births)': 913.1,
    'Infant survival rate%': 91.31,
    INVPRIMARYTEACHERS: 0.010238495,
    PRIMARYTEACHERS: 97.6706077,
    INVLOWERTEACHERS: 0.002259385,
    LOWERTEACHERS: 442.5982659,
    INVUPPERTEACHERS: 0.002878015,
    '': 347.4616935
  },
  {
    countryyearcode: 'ROU2014',
    countryname: 'Romania',
    countrycode: 'ROU',
    'Government revenue per capita (constant 2015 USD)': 2943.23,
    year: 2014,
    region: 'ECS',
    incomelevel: 'UMC',
    'People using at least basic sanitation services (% of population)': 82.23,
    'People using safely managed sanitation services (% of population)': 70.49,
    'People using at least basic drinking water services (% of population)': 100,
    'People using safely managed drinking water services (% of population)': 81.91,
    'Immunization, DPT (% of children ages 12-23 months)': 94,
    'School percent': 69.83,
    'U5 survival %': 99.01,
    'Maternal survival rate %': 99.99,
    'Government Effectiveness: Estimate': 0.226,
    'Control of Corruption: Estimate': -0.2239,
    'Political Stability and Absence of Violence/Terrorism: Estimate': 0.0491,
    'Regulatory Quality: Estimate': 0.6008,
    'Rule of Law: Estimate': 0.2422,
    'Voice and Accountability: Estimate': 0.4281,
    'Pop total': 19908979,
    'Pop<5': 1012689,
    'Female Pop15-49': 4748990,
    'Number of infants surviving to 1yr': 198397,
    'Number of births': 203669,
    'Number of children surviving to five ': 216586,
    'Number of under-five deaths': 1997,
    'Number of maternal deaths': 31,
    'In school: Primary school': 0.93,
    'In school: Lower school': 0.92,
    'In school: Upper school': 0.82,
    'School age population, primary education, both sexes (number)': 1041631,
    'School age population, primary education, female (number)': 506985,
    'School age population, primary education, male (number)': 534646,
    'School age population, lower secondary education, both sexes (number)': 830522,
    'School age population, lower secondary education, female (number)': 403998,
    'School age population, lower secondary education, male (number)': 426524,
    'School age population, upper secondary education, both sexes (number)': 873903,
    'School age population, upper secondary education, female (number)': 423355,
    'School age population, upper secondary education, male (number)': 450548,
    'Maternal mortality ratio (per 100,000 live births)': 15,
    'Maternal survival per 100,000 live births': 99985,
    'U5 mortality rate(per 1,000 live births)': 9.9,
    'U5 survival rate (per 1000 live births)': 990.1,
    'Infant mortality rate (per 1000 live births)': 8.3,
    'Infant survival (per 1000 live births)': 991.7,
    'Infant survival rate%': 99.17,
    INVPRIMARYTEACHERS: 0.048824392,
    PRIMARYTEACHERS: 20.48156596,
    INVLOWERTEACHERS: 0.089324545,
    LOWERTEACHERS: 11.19513116,
    INVUPPERTEACHERS: 0.065207466,
    '': 15.33566728
  },
  {
    countryyearcode: 'TCD1982',
    countryname: 'Chad',
    countrycode: 'TCD',
    'Government revenue per capita (constant 2015 USD)': null,
    year: 1982,
    region: 'SSF',
    incomelevel: 'LIC',
    'People using at least basic sanitation services (% of population)': null,
    'People using safely managed sanitation services (% of population)': null,
    'People using at least basic drinking water services (% of population)': null,
    'People using safely managed drinking water services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': null,
    'School percent': null,
    'U5 survival %': 76.47,
    'Maternal survival rate %': null,
    'Government Effectiveness: Estimate': null,
    'Control of Corruption: Estimate': null,
    'Political Stability and Absence of Violence/Terrorism: Estimate': null,
    'Regulatory Quality: Estimate': null,
    'Rule of Law: Estimate': null,
    'Voice and Accountability: Estimate': null,
    'Pop total': 4622828,
    'Pop<5': 857812,
    'Female Pop15-49': 981181,
    'Number of infants surviving to 1yr': 177019,
    'Number of births': 211774,
    'Number of children surviving to five ': 151410,
    'Number of under-five deaths': 48644,
    'Number of maternal deaths': null,
    'In school: Primary school': null,
    'In school: Lower school': null,
    'In school: Upper school': null,
    'School age population, primary education, both sexes (number)': 758488,
    'School age population, primary education, female (number)': 378472,
    'School age population, primary education, male (number)': 380016,
    'School age population, lower secondary education, both sexes (number)': 402147,
    'School age population, lower secondary education, female (number)': 201085,
    'School age population, lower secondary education, male (number)': 201062,
    'School age population, upper secondary education, both sexes (number)': 268729,
    'School age population, upper secondary education, female (number)': 135016,
    'School age population, upper secondary education, male (number)': 133713,
    'Maternal mortality ratio (per 100,000 live births)': null,
    'Maternal survival per 100,000 live births': null,
    'U5 mortality rate(per 1,000 live births)': 235.3,
    'U5 survival rate (per 1000 live births)': 764.7,
    'Infant mortality rate (per 1000 live births)': 121.6,
    'Infant survival (per 1000 live births)': 878.4,
    'Infant survival rate%': 87.84,
    INVPRIMARYTEACHERS: null,
    PRIMARYTEACHERS: null,
    INVLOWERTEACHERS: null,
    LOWERTEACHERS: null,
    INVUPPERTEACHERS: null,
    '': null
  },
  {
    countryyearcode: 'WSM1993',
    countryname: 'Samoa',
    countrycode: 'WSM',
    'Government revenue per capita (constant 2015 USD)': 708.01,
    year: 1993,
    region: 'EAS',
    incomelevel: 'UMC',
    'People using at least basic sanitation services (% of population)': null,
    'People using safely managed sanitation services (% of population)': null,
    'People using at least basic drinking water services (% of population)': null,
    'People using safely managed drinking water services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': 92,
    'School percent': 66.94125000000001,
    'U5 survival %': 97.29,
    'Maternal survival rate %': null,
    'Government Effectiveness: Estimate': null,
    'Control of Corruption: Estimate': null,
    'Political Stability and Absence of Violence/Terrorism: Estimate': null,
    'Regulatory Quality: Estimate': null,
    'Rule of Law: Estimate': null,
    'Voice and Accountability: Estimate': null,
    'Pop total': 171362,
    'Pop<5': 25598,
    'Female Pop15-49': 38516,
    'Number of infants surviving to 1yr': 5359,
    'Number of births': 5644,
    'Number of children surviving to five ': 4634,
    'Number of under-five deaths': 151,
    'Number of maternal deaths': null,
    'In school: Primary school': null,
    'In school: Lower school': null,
    'In school: Upper school': null,
    'School age population, primary education, both sexes (number)': 26495,
    'School age population, primary education, female (number)': 12447,
    'School age population, primary education, male (number)': 14048,
    'School age population, lower secondary education, both sexes (number)': 8398,
    'School age population, lower secondary education, female (number)': 3915,
    'School age population, lower secondary education, male (number)': 4483,
    'School age population, upper secondary education, both sexes (number)': 19928,
    'School age population, upper secondary education, female (number)': 9088,
    'School age population, upper secondary education, male (number)': 10840,
    'Maternal mortality ratio (per 100,000 live births)': null,
    'Maternal survival per 100,000 live births': null,
    'U5 mortality rate(per 1,000 live births)': 27.1,
    'U5 survival rate (per 1000 live births)': 972.9,
    'Infant mortality rate (per 1000 live births)': 22.8,
    'Infant survival (per 1000 live births)': 977.2,
    'Infant survival rate%': 97.72,
    INVPRIMARYTEACHERS: null,
    PRIMARYTEACHERS: null,
    INVLOWERTEACHERS: null,
    LOWERTEACHERS: null,
    INVUPPERTEACHERS: null,
    '': null
  }
];

testIndices.forEach((index, i) => {
  test('data row is as expected', () => {
    expect(data[index]).toStrictEqual(testData[i]);
  });
});
