/* eslint-disable max-len */
import {data} from '../src/index';

const testIndices = [0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000];
const testData = [
  {
    countryyearcode: 'ABW1980',
    countryname: 'Aruba',
    countrycode: 'ABW',
    'Government revenue per capita (constant 2015 USD)': null,
    year: 1980,
    region: 'LCN',
    incomelevel: 'HIC',
    'People using at least basic sanitation services (% of population)': null,
    'People using safely managed sanitation services (% of population)': null,
    'People using at least basic drinking water services (% of population)': null,
    'People using safely managed drinking water services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': null,
    'School percent': null,
    'U5 survival %': null,
    'Maternal survival rate %': null,
    'Government Effectiveness: Estimate': null,
    'Control of Corruption: Estimate': null,
    'Political Stability and Absence of Violence/Terrorism: Estimate': null,
    'Regulatory Quality: Estimate': null,
    'Rule of Law: Estimate': null,
    'Voice and Accountability: Estimate': null,
    'Pop total': 62267,
    'Pop<5': 6356,
    'Female Pop15-49': 17769,
    'Number of infants surviving to 1yr': 1281,
    'Number of births': 1374,
    'Number of children surviving to five ': 1234,
    'Number of under-five deaths': null,
    'Number of maternal deaths': null,
    'In school: Primary school': null,
    'In school: Lower school': null,
    'In school: Upper school': null,
    'School age population, primary education, both sexes (number)': 6384,
    'School age population, primary education, female (number)': 3119,
    'School age population, primary education, male (number)': 3265,
    'School age population, lower secondary education, both sexes (number)': 2515,
    'School age population, lower secondary education, female (number)': 1230,
    'School age population, lower secondary education, male (number)': 1285,
    'School age population, upper secondary education, both sexes (number)': 4162,
    'School age population, upper secondary education, female (number)': 2041,
    'School age population, upper secondary education, male (number)': 2121,
    'Maternal mortality ratio (per 100,000 live births)': null,
    'Maternal survival per 100,000 live births': null,
    'U5 mortality rate(per 1,000 live births)': null,
    'U5 survival rate (per 1000 live births)': null,
    'Infant mortality rate (per 1000 live births)': null,
    'Infant survival (per 1000 live births)': null,
    'Infant survival rate%': null,
    'Primary school teachers to pupils': null,
    'Primary school pupils to teachers': null,
    'Lower school teachers to pupils': null,
    'Lower school pupils to teachers': null,
    'Upper school teachers to pupils': null,
    'Upper school pupils to teachers': null
  },
  {
    countryyearcode: 'BLZ1991',
    countryname: 'Belize',
    countrycode: 'BLZ',
    'Government revenue per capita (constant 2015 USD)': 1098.92,
    year: 1991,
    region: 'LCN',
    incomelevel: 'UMC',
    'People using at least basic sanitation services (% of population)': null,
    'People using safely managed sanitation services (% of population)': null,
    'People using at least basic drinking water services (% of population)': null,
    'People using safely managed drinking water services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': 82,
    'School percent': 61.94,
    'U5 survival %': 96.39,
    'Maternal survival rate %': null,
    'Government Effectiveness: Estimate': null,
    'Control of Corruption: Estimate': null,
    'Political Stability and Absence of Violence/Terrorism: Estimate': null,
    'Regulatory Quality: Estimate': null,
    'Rule of Law: Estimate': null,
    'Voice and Accountability: Estimate': null,
    'Pop total': 186462,
    'Pop<5': 30100,
    'Female Pop15-49': 42007,
    'Number of infants surviving to 1yr': 6112,
    'Number of births': 6609,
    'Number of children surviving to five ': 5708,
    'Number of under-five deaths': 238,
    'Number of maternal deaths': null,
    'In school: Primary school': null,
    'In school: Lower school': null,
    'In school: Upper school': null,
    'School age population, primary education, both sexes (number)': 32575,
    'School age population, primary education, female (number)': 16110,
    'School age population, primary education, male (number)': 16465,
    'School age population, lower secondary education, both sexes (number)': 18536,
    'School age population, lower secondary education, female (number)': 9176,
    'School age population, lower secondary education, male (number)': 9360,
    'School age population, upper secondary education, both sexes (number)': 8706,
    'School age population, upper secondary education, female (number)': 4335,
    'School age population, upper secondary education, male (number)': 4371,
    'Maternal mortality ratio (per 100,000 live births)': null,
    'Maternal survival per 100,000 live births': null,
    'U5 mortality rate(per 1,000 live births)': 36.1,
    'U5 survival rate (per 1000 live births)': 963.9,
    'Infant mortality rate (per 1000 live births)': 29.6,
    'Infant survival (per 1000 live births)': 970.4,
    'Infant survival rate%': 97.04,
    'Primary school teachers to pupils': null,
    'Primary school pupils to teachers': null,
    'Lower school teachers to pupils': null,
    'Lower school pupils to teachers': null,
    'Upper school teachers to pupils': null,
    'Upper school pupils to teachers': null
  },
  {
    countryyearcode: 'CYM2002',
    countryname: 'Cayman Islands',
    countrycode: 'CYM',
    'Government revenue per capita (constant 2015 USD)': 0,
    year: 2002,
    region: 'LCN',
    incomelevel: 'HIC',
    'People using at least basic sanitation services (% of population)': 83.65,
    'People using safely managed sanitation services (% of population)': null,
    'People using at least basic drinking water services (% of population)': 96.13,
    'People using safely managed drinking water services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': null,
    'School percent': 62.54,
    'U5 survival %': null,
    'Maternal survival rate %': null,
    'Government Effectiveness: Estimate': 1.9008,
    'Control of Corruption: Estimate': 1.3107,
    'Political Stability and Absence of Violence/Terrorism: Estimate': 0.7926,
    'Regulatory Quality: Estimate': 1.4225,
    'Rule of Law: Estimate': 1.4694,
    'Voice and Accountability: Estimate': 1.5733,
    'Pop total': 42456,
    'Pop<5': 2993,
    'Female Pop15-49': 13687,
    'Number of infants surviving to 1yr': 639,
    'Number of births': 578,
    'Number of children surviving to five ': 562,
    'Number of under-five deaths': null,
    'Number of maternal deaths': null,
    'In school: Primary school': 0,
    'In school: Lower school': 0,
    'In school: Upper school': 0,
    'School age population, primary education, both sexes (number)': 3752,
    'School age population, primary education, female (number)': 1860,
    'School age population, primary education, male (number)': 1892,
    'School age population, lower secondary education, both sexes (number)': 1519,
    'School age population, lower secondary education, female (number)': 750,
    'School age population, lower secondary education, male (number)': 769,
    'School age population, upper secondary education, both sexes (number)': 1362,
    'School age population, upper secondary education, female (number)': 685,
    'School age population, upper secondary education, male (number)': 677,
    'Maternal mortality ratio (per 100,000 live births)': null,
    'Maternal survival per 100,000 live births': null,
    'U5 mortality rate(per 1,000 live births)': null,
    'U5 survival rate (per 1000 live births)': null,
    'Infant mortality rate (per 1000 live births)': null,
    'Infant survival (per 1000 live births)': null,
    'Infant survival rate%': null,
    'Primary school teachers to pupils': 0.063965885,
    'Primary school pupils to teachers': 15.63333333,
    'Lower school teachers to pupils': 0.074391047,
    'Lower school pupils to teachers': 13.44247788,
    'Upper school teachers to pupils': 0.086637298,
    'Upper school pupils to teachers': 11.54237288
  },
  {
    countryyearcode: 'GHA2013',
    countryname: 'Ghana',
    countrycode: 'GHA',
    'Government revenue per capita (constant 2015 USD)': 243.41,
    year: 2013,
    region: 'SSF',
    incomelevel: 'LMC',
    'People using at least basic sanitation services (% of population)': 17.29,
    'People using safely managed sanitation services (% of population)': 10.06,
    'People using at least basic drinking water services (% of population)': 77.92,
    'People using safely managed drinking water services (% of population)': 29.93,
    'Immunization, DPT (% of children ages 12-23 months)': 90,
    'School percent': 62.68,
    'U5 survival %': 93.95,
    'Maternal survival rate %': 99.7,
    'Government Effectiveness: Estimate': -0.1369,
    'Control of Corruption: Estimate': -0.0966,
    'Political Stability and Absence of Violence/Terrorism: Estimate': 0.0606,
    'Regulatory Quality: Estimate': 0.0618,
    'Rule of Law: Estimate': 0.1543,
    'Voice and Accountability: Estimate': 0.4389,
    'Pop total': 27525597,
    'Pop<5': 4044686,
    'Female Pop15-49': 6894918,
    'Number of infants surviving to 1yr': 833318,
    'Number of births': 895716,
    'Number of children surviving to five ': 742554,
    'Number of under-five deaths': 52633,
    'Number of maternal deaths': 2700,
    'In school: Primary school': 0.84,
    'In school: Lower school': 0.81,
    'In school: Upper school': 0.6,
    'School age population, primary education, both sexes (number)': 3869823,
    'School age population, primary education, female (number)': 1894842,
    'School age population, primary education, male (number)': 1974981,
    'School age population, lower secondary education, both sexes (number)': 1791906,
    'School age population, lower secondary education, female (number)': 876547,
    'School age population, lower secondary education, male (number)': 915359,
    'School age population, upper secondary education, both sexes (number)': 1685832,
    'School age population, upper secondary education, female (number)': 824137,
    'School age population, upper secondary education, male (number)': 861695,
    'Maternal mortality ratio (per 100,000 live births)': 305,
    'Maternal survival per 100,000 live births': 99695,
    'U5 mortality rate(per 1,000 live births)': 60.5,
    'U5 survival rate (per 1000 live births)': 939.5,
    'Infant mortality rate (per 1000 live births)': 42.2,
    'Infant survival (per 1000 live births)': 957.8,
    'Infant survival rate%': 95.78,
    'Primary school teachers to pupils': 0.033489645,
    'Primary school pupils to teachers': 29.85997577,
    'Lower school teachers to pupils': 0.052344822,
    'Lower school pupils to teachers': 19.10408648,
    'Upper school teachers to pupils': 0.024107384,
    'Upper school pupils to teachers': 41.48106592
  },
  {
    countryyearcode: 'ISR1981',
    countryname: 'Israel',
    countrycode: 'ISR',
    'Government revenue per capita (constant 2015 USD)': null,
    year: 1981,
    region: 'MEA',
    incomelevel: 'HIC',
    'People using at least basic sanitation services (% of population)': null,
    'People using safely managed sanitation services (% of population)': null,
    'People using at least basic drinking water services (% of population)': null,
    'People using safely managed drinking water services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': 91,
    'School percent': 65.75,
    'U5 survival %': 98.27,
    'Maternal survival rate %': null,
    'Government Effectiveness: Estimate': null,
    'Control of Corruption: Estimate': null,
    'Political Stability and Absence of Violence/Terrorism: Estimate': null,
    'Regulatory Quality: Estimate': null,
    'Rule of Law: Estimate': null,
    'Voice and Accountability: Estimate': null,
    'Pop total': 3956000,
    'Pop<5': 455265,
    'Female Pop15-49': 928288,
    'Number of infants surviving to 1yr': 87659,
    'Number of births': 94807,
    'Number of children surviving to five ': 91618,
    'Number of under-five deaths': 1646,
    'Number of maternal deaths': null,
    'In school: Primary school': null,
    'In school: Lower school': null,
    'In school: Upper school': null,
    'School age population, primary education, both sexes (number)': 478069,
    'School age population, primary education, female (number)': 232911,
    'School age population, primary education, male (number)': 245158,
    'School age population, lower secondary education, both sexes (number)': 201482,
    'School age population, lower secondary education, female (number)': 97885,
    'School age population, lower secondary education, male (number)': 103597,
    'School age population, upper secondary education, both sexes (number)': 194927,
    'School age population, upper secondary education, female (number)': 94599,
    'School age population, upper secondary education, male (number)': 100328,
    'Maternal mortality ratio (per 100,000 live births)': null,
    'Maternal survival per 100,000 live births': null,
    'U5 mortality rate(per 1,000 live births)': 17.3,
    'U5 survival rate (per 1000 live births)': 982.7,
    'Infant mortality rate (per 1000 live births)': 14.7,
    'Infant survival (per 1000 live births)': 985.3,
    'Infant survival rate%': 98.53,
    'Primary school teachers to pupils': 0.086740617,
    'Primary school pupils to teachers': 11.52862448,
    'Lower school teachers to pupils': null,
    'Lower school pupils to teachers': null,
    'Upper school teachers to pupils': null,
    'Upper school pupils to teachers': null
  },
  {
    countryyearcode: 'LVA1992',
    countryname: 'Latvia',
    countrycode: 'LVA',
    'Government revenue per capita (constant 2015 USD)': null,
    year: 1992,
    region: 'ECS',
    incomelevel: 'HIC',
    'People using at least basic sanitation services (% of population)': null,
    'People using safely managed sanitation services (% of population)': null,
    'People using at least basic drinking water services (% of population)': null,
    'People using safely managed drinking water services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': 87,
    'School percent': 65.15,
    'U5 survival %': 98.05,
    'Maternal survival rate %': null,
    'Government Effectiveness: Estimate': null,
    'Control of Corruption: Estimate': null,
    'Political Stability and Absence of Violence/Terrorism: Estimate': null,
    'Regulatory Quality: Estimate': null,
    'Rule of Law: Estimate': null,
    'Voice and Accountability: Estimate': null,
    'Pop total': 2614338,
    'Pop<5': 184100,
    'Female Pop15-49': 636881,
    'Number of infants surviving to 1yr': 35710,
    'Number of births': 32991,
    'Number of children surviving to five ': 41826,
    'Number of under-five deaths': 691,
    'Number of maternal deaths': null,
    'In school: Primary school': null,
    'In school: Lower school': null,
    'In school: Upper school': null,
    'School age population, primary education, both sexes (number)': 152378,
    'School age population, primary education, female (number)': 74608,
    'School age population, primary education, male (number)': 77770,
    'School age population, lower secondary education, both sexes (number)': 171058,
    'School age population, lower secondary education, female (number)': 84296,
    'School age population, lower secondary education, male (number)': 86762,
    'School age population, upper secondary education, both sexes (number)': 109937,
    'School age population, upper secondary education, female (number)': 53901,
    'School age population, upper secondary education, male (number)': 56036,
    'Maternal mortality ratio (per 100,000 live births)': null,
    'Maternal survival per 100,000 live births': null,
    'U5 mortality rate(per 1,000 live births)': 19.5,
    'U5 survival rate (per 1000 live births)': 980.5,
    'Infant mortality rate (per 1000 live births)': 15.2,
    'Infant survival (per 1000 live births)': 984.8,
    'Infant survival rate%': 98.48,
    'Primary school teachers to pupils': 0.062134954,
    'Primary school pupils to teachers': 16.09400084,
    'Lower school teachers to pupils': 0.1014802,
    'Lower school pupils to teachers': 9.854139063,
    'Upper school teachers to pupils': 0.098392716,
    'Upper school pupils to teachers': 10.16335398
  },
  {
    countryyearcode: 'NCL2003',
    countryname: 'New Caledonia',
    countrycode: 'NCL',
    'Government revenue per capita (constant 2015 USD)': 0,
    year: 2003,
    region: 'EAS',
    incomelevel: 'HIC',
    'People using at least basic sanitation services (% of population)': 100,
    'People using safely managed sanitation services (% of population)': null,
    'People using at least basic drinking water services (% of population)': 95.34,
    'People using safely managed drinking water services (% of population)': 87.71,
    'Immunization, DPT (% of children ages 12-23 months)': null,
    'School percent': 0,
    'U5 survival %': null,
    'Maternal survival rate %': null,
    'Government Effectiveness: Estimate': null,
    'Control of Corruption: Estimate': null,
    'Political Stability and Absence of Violence/Terrorism: Estimate': null,
    'Regulatory Quality: Estimate': null,
    'Rule of Law: Estimate': null,
    'Voice and Accountability: Estimate': null,
    'Pop total': 225296,
    'Pop<5': 21297,
    'Female Pop15-49': 59588,
    'Number of infants surviving to 1yr': 4392,
    'Number of births': 4317,
    'Number of children surviving to five ': 4586,
    'Number of under-five deaths': null,
    'Number of maternal deaths': null,
    'In school: Primary school': 0,
    'In school: Lower school': 0,
    'In school: Upper school': 0,
    'School age population, primary education, both sexes (number)': 0,
    'School age population, primary education, female (number)': 0,
    'School age population, primary education, male (number)': 0,
    'School age population, lower secondary education, both sexes (number)': 0,
    'School age population, lower secondary education, female (number)': 0,
    'School age population, lower secondary education, male (number)': 0,
    'School age population, upper secondary education, both sexes (number)': 0,
    'School age population, upper secondary education, female (number)': 0,
    'School age population, upper secondary education, male (number)': 0,
    'Maternal mortality ratio (per 100,000 live births)': null,
    'Maternal survival per 100,000 live births': null,
    'U5 mortality rate(per 1,000 live births)': null,
    'U5 survival rate (per 1000 live births)': null,
    'Infant mortality rate (per 1000 live births)': null,
    'Infant survival (per 1000 live births)': null,
    'Infant survival rate%': null,
    'Primary school teachers to pupils': null,
    'Primary school pupils to teachers': null,
    'Lower school teachers to pupils': null,
    'Lower school pupils to teachers': null,
    'Upper school teachers to pupils': null,
    'Upper school pupils to teachers': null
  },
  {
    countryyearcode: 'QAT2014',
    countryname: 'Qatar',
    countrycode: 'QAT',
    'Government revenue per capita (constant 2015 USD)': 31859.03,
    year: 2014,
    region: 'MEA',
    incomelevel: 'HIC',
    'People using at least basic sanitation services (% of population)': 100,
    'People using safely managed sanitation services (% of population)': 88.5,
    'People using at least basic drinking water services (% of population)': 99.75,
    'People using safely managed drinking water services (% of population)': 96.36,
    'Immunization, DPT (% of children ages 12-23 months)': 89,
    'School percent': null,
    'U5 survival %': 99.19,
    'Maternal survival rate %': 99.99,
    'Government Effectiveness: Estimate': 0.9407,
    'Control of Corruption: Estimate': 0.9838,
    'Political Stability and Absence of Violence/Terrorism: Estimate': 0.9775,
    'Regulatory Quality: Estimate': 0.5696,
    'Rule of Law: Estimate': 0.8625,
    'Voice and Accountability: Estimate': -1.1334,
    'Pop total': 2214465,
    'Pop<5': 120337,
    'Female Pop15-49': 361417,
    'Number of infants surviving to 1yr': 24336,
    'Number of births': 23038,
    'Number of children surviving to five ': 23327,
    'Number of under-five deaths': 180,
    'Number of maternal deaths': 2,
    'In school: Primary school': 0.91,
    'In school: Lower school': 0.88,
    'In school: Upper school': 0.64,
    'School age population, primary education, both sexes (number)': 118579,
    'School age population, primary education, female (number)': 57340,
    'School age population, primary education, male (number)': 61239,
    'School age population, lower secondary education, both sexes (number)': 48046,
    'School age population, lower secondary education, female (number)': 22472,
    'School age population, lower secondary education, male (number)': 25574,
    'School age population, upper secondary education, both sexes (number)': 57436,
    'School age population, upper secondary education, female (number)': 20355,
    'School age population, upper secondary education, male (number)': 37081,
    'Maternal mortality ratio (per 100,000 live births)': 7,
    'Maternal survival per 100,000 live births': 99993,
    'U5 mortality rate(per 1,000 live births)': 8.1,
    'U5 survival rate (per 1000 live births)': 991.9,
    'Infant mortality rate (per 1000 live births)': 7,
    'Infant survival (per 1000 live births)': 993,
    'Infant survival rate%': 99.3,
    'Primary school teachers to pupils': 0.088363032,
    'Primary school pupils to teachers': 11.3169498,
    'Lower school teachers to pupils': 0.091807851,
    'Lower school pupils to teachers': 10.89231467,
    'Upper school teachers to pupils': 0.074639599,
    'Upper school pupils to teachers': 13.39771402
  },
  {
    countryyearcode: 'TCA1982',
    countryname: 'Turks and Caicos Islands',
    countrycode: 'TCA',
    'Government revenue per capita (constant 2015 USD)': 0,
    year: 1982,
    region: 'LCN',
    incomelevel: 'HIC',
    'People using at least basic sanitation services (% of population)': null,
    'People using safely managed sanitation services (% of population)': null,
    'People using at least basic drinking water services (% of population)': null,
    'People using safely managed drinking water services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': null,
    'School percent': null,
    'U5 survival %': 97.63,
    'Maternal survival rate %': null,
    'Government Effectiveness: Estimate': null,
    'Control of Corruption: Estimate': null,
    'Political Stability and Absence of Violence/Terrorism: Estimate': null,
    'Regulatory Quality: Estimate': null,
    'Rule of Law: Estimate': null,
    'Voice and Accountability: Estimate': null,
    'Pop total': 8355,
    'Pop<5': 1054,
    'Female Pop15-49': 1921,
    'Number of infants surviving to 1yr': 216,
    'Number of births': 249,
    'Number of children surviving to five ': 201,
    'Number of under-five deaths': 6,
    'Number of maternal deaths': null,
    'In school: Primary school': 0,
    'In school: Lower school': 0,
    'In school: Upper school': 0,
    'School age population, primary education, both sexes (number)': 1265,
    'School age population, primary education, female (number)': 630,
    'School age population, primary education, male (number)': 635,
    'School age population, lower secondary education, both sexes (number)': 670,
    'School age population, lower secondary education, female (number)': 337,
    'School age population, lower secondary education, male (number)': 333,
    'School age population, upper secondary education, both sexes (number)': 440,
    'School age population, upper secondary education, female (number)': 216,
    'School age population, upper secondary education, male (number)': 224,
    'Maternal mortality ratio (per 100,000 live births)': null,
    'Maternal survival per 100,000 live births': null,
    'U5 mortality rate(per 1,000 live births)': 23.7,
    'U5 survival rate (per 1000 live births)': 976.3,
    'Infant mortality rate (per 1000 live births)': 18.8,
    'Infant survival (per 1000 live births)': 981.2,
    'Infant survival rate%': 98.12,
    'Primary school teachers to pupils': null,
    'Primary school pupils to teachers': null,
    'Lower school teachers to pupils': null,
    'Lower school pupils to teachers': null,
    'Upper school teachers to pupils': null,
    'Upper school pupils to teachers': null
  },
  {
    countryyearcode: 'VUT1993',
    countryname: 'Vanuatu',
    countrycode: 'VUT',
    'Government revenue per capita (constant 2015 USD)': 533.39,
    year: 1993,
    region: 'EAS',
    incomelevel: 'LMC',
    'People using at least basic sanitation services (% of population)': null,
    'People using safely managed sanitation services (% of population)': null,
    'People using at least basic drinking water services (% of population)': null,
    'People using safely managed drinking water services (% of population)': null,
    'Immunization, DPT (% of children ages 12-23 months)': 86,
    'School percent': 44.7575,
    'U5 survival %': 96.78,
    'Maternal survival rate %': null,
    'Government Effectiveness: Estimate': null,
    'Control of Corruption: Estimate': null,
    'Political Stability and Absence of Violence/Terrorism: Estimate': null,
    'Regulatory Quality: Estimate': null,
    'Rule of Law: Estimate': null,
    'Voice and Accountability: Estimate': null,
    'Pop total': 162548,
    'Pop<5': 27800,
    'Female Pop15-49': 37052,
    'Number of infants surviving to 1yr': 5669,
    'Number of births': 5949,
    'Number of children surviving to five ': 5238,
    'Number of under-five deaths': 189,
    'Number of maternal deaths': null,
    'In school: Primary school': null,
    'In school: Lower school': null,
    'In school: Upper school': null,
    'School age population, primary education, both sexes (number)': 27177,
    'School age population, primary education, female (number)': 13034,
    'School age population, primary education, male (number)': 14143,
    'School age population, lower secondary education, both sexes (number)': 15424,
    'School age population, lower secondary education, female (number)': 7391,
    'School age population, lower secondary education, male (number)': 8033,
    'School age population, upper secondary education, both sexes (number)': 9841,
    'School age population, upper secondary education, female (number)': 4772,
    'School age population, upper secondary education, male (number)': 5069,
    'Maternal mortality ratio (per 100,000 live births)': null,
    'Maternal survival per 100,000 live births': null,
    'U5 mortality rate(per 1,000 live births)': 32.2,
    'U5 survival rate (per 1000 live births)': 967.8,
    'Infant mortality rate (per 1000 live births)': 26.7,
    'Infant survival (per 1000 live births)': 973.3,
    'Infant survival rate%': 97.33,
    'Primary school teachers to pupils': null,
    'Primary school pupils to teachers': null,
    'Lower school teachers to pupils': null,
    'Lower school pupils to teachers': null,
    'Upper school teachers to pupils': null,
    'Upper school pupils to teachers': null
  }
];

testIndices.forEach((index, i) => {
  test('data row is as expected', () => {
    expect(data[index]).toStrictEqual(testData[i]);
  });
});
